### ISSUE TITLE
Getting Following Error

### ISSUE THREAD

**Issue by donavanbecker** [masx200/no-ip-ddns-ipv6#1]
Have `noip` defined [here](https://github.com/donavanbecker/homebridge-noip/blob/370184e98aabf771fa374e1631bc01d363e005c1/src/devices/contactsensor.ts#L32-L36)
Using it [here](https://github.com/donavanbecker/homebridge-noip/blob/370184e98aabf771fa374e1631bc01d363e005c1/src/devices/contactsensor.ts#L104-L109)

```RequestError: connect ENETUNREACH xxxx:xxxx:xxxx:x::xxx:xx
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-noip/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/usr/local/lib/node_modules/homebridge-noip/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  code: 'ENETUNREACH',
  timings: {
    start: 1628534874753,
    socket: 1628534874755,
    lookup: 1628534874757,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1628534874759,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 2,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 6
    }
  }
}
Got response: 200
nochg 196.192.1.1```

**Comment by masx200** [comment]
It seems that this is not an error, because you do not have an ipv6 address so "ENETUNREACH", this does not affect the use of ipv4.

**Comment by masx200** [comment]
This is just a fork of no-ip, to solve the problem of ipv6, you can fork this code repository to modify it yourself.

**Comment by masx200** [comment]
https://github.com/masx200/no-ip-ddns-ipv6/blob/01586114daeba8f445f9228ad134dfeac423801c/lib/no-ip.js#L67

**Comment by masx200** [comment]
You can initiate a pull request.

**Comment by donavanbecker** [comment]
> This is just a fork of no-ip, to solve the problem of ipv6, you can fork this code repository to modify it yourself.

I switched to no-ip. So good to go.
